// Mock tournament data — US soccer tournaments
// Coordinates are normalized to a stylized 1000x600 US map viewBox

window.TOURNAMENTS = [
  {
    id: "t1",
    name: "Coastal Classic Cup",
    host: "Pacific Soccer Alliance",
    city: "San Diego",
    state: "CA",
    region: "West",
    dateStart: "2026-06-12",
    dateEnd: "2026-06-14",
    age: ["U10", "U11", "U12", "U13", "U14"],
    gender: "Both",
    level: "Upper",
    format: "11v11",
    surface: "Grass",
    fee: 695,
    teams: 84,
    rating: 4.8,
    reviews: 142,
    status: "Open",
    featured: true,
    sanctioned: "US Club",
    spotsLeft: 6,
    mapX: 88, mapY: 410,
    img: null,
    scene: "beach",
    tagline: "Sun, surf, and 84 teams"
  },
  {
    id: "t2",
    name: "Rocky Mountain Showcase",
    host: "Mile High Soccer Club",
    city: "Denver",
    state: "CO",
    region: "Mountain",
    dateStart: "2026-07-04",
    dateEnd: "2026-07-06",
    age: ["U13", "U14", "U15", "U16", "U17", "U18"],
    gender: "Boys",
    level: "Highest",
    format: "11v11",
    surface: "Grass",
    fee: 1250,
    teams: 128,
    rating: 4.9,
    reviews: 318,
    status: "Open",
    featured: true,
    sanctioned: "US Soccer",
    spotsLeft: 3,
    mapX: 410, mapY: 290,
    img: null,
    scene: "mountain",
    tagline: "ECNL & MLS Next scouts on-site"
  },
  {
    id: "t3",
    name: "Lone Star 3v3 Frenzy",
    host: "Texas Youth Soccer",
    city: "Austin",
    state: "TX",
    region: "South",
    dateStart: "2026-05-30",
    dateEnd: "2026-05-31",
    age: ["U6", "U7", "U8", "U9", "U10"],
    gender: "Both",
    level: "Middle",
    format: "3v3",
    surface: "Turf",
    fee: 175,
    teams: 220,
    rating: 4.6,
    reviews: 89,
    status: "Open",
    featured: false,
    sanctioned: "Regional",
    spotsLeft: 32,
    mapX: 540, mapY: 470,
    img: null,
    scene: "trophy",
    tagline: "Fastest weekend in Texas"
  },
  {
    id: "t4",
    name: "Bay State Invitational",
    host: "New England FC",
    city: "Boston",
    state: "MA",
    region: "Northeast",
    dateStart: "2026-08-22",
    dateEnd: "2026-08-24",
    age: ["U11", "U12", "U13", "U14"],
    gender: "Girls",
    level: "Upper",
    format: "9v9",
    surface: "Turf",
    fee: 825,
    teams: 64,
    rating: 4.7,
    reviews: 96,
    status: "Open",
    featured: false,
    sanctioned: "US Club",
    spotsLeft: 11,
    mapX: 870, mapY: 215,
    img: null,
    scene: "city",
    tagline: "College coaches welcomed"
  },
  {
    id: "t5",
    name: "Sunshine State Showdown",
    host: "Florida Soccer Federation",
    city: "Orlando",
    state: "FL",
    region: "Southeast",
    dateStart: "2026-12-27",
    dateEnd: "2026-12-30",
    age: ["U9", "U10", "U11", "U12", "U13", "U14", "U15"],
    gender: "Both",
    level: "Highest",
    format: "11v11",
    surface: "Grass",
    fee: 1450,
    teams: 256,
    rating: 4.9,
    reviews: 504,
    status: "Open",
    featured: true,
    sanctioned: "US Soccer",
    spotsLeft: 12,
    mapX: 820, mapY: 490,
    img: null,
    scene: "trophy",
    tagline: "Holiday week marquee event"
  },
  {
    id: "t6",
    name: "Great Lakes Futsal Open",
    host: "Chicago Futsal Academy",
    city: "Chicago",
    state: "IL",
    region: "Midwest",
    dateStart: "2026-02-14",
    dateEnd: "2026-02-15",
    age: ["U8", "U9", "U10", "U11", "U12"],
    gender: "Both",
    level: "Middle",
    format: "5v5",
    surface: "Turf",
    fee: 295,
    teams: 96,
    rating: 4.5,
    reviews: 73,
    status: "Closed",
    featured: false,
    sanctioned: "Regional",
    spotsLeft: 0,
    mapX: 615, mapY: 280,
    img: null,
    scene: "indoor",
    tagline: "Indoor speed, all weekend"
  },
  {
    id: "t7",
    name: "Cascade Cup",
    host: "Pacific Northwest United",
    city: "Portland",
    state: "OR",
    region: "West",
    dateStart: "2026-07-18",
    dateEnd: "2026-07-20",
    age: ["U13", "U14", "U15"],
    gender: "Girls",
    level: "Upper",
    format: "11v11",
    surface: "Turf",
    fee: 950,
    teams: 72,
    rating: 4.6,
    reviews: 51,
    status: "Open",
    featured: false,
    sanctioned: "US Club",
    spotsLeft: 18,
    mapX: 110, mapY: 175,
    img: null,
    scene: "forest",
    tagline: "Forest, fields, full whistle"
  },
  {
    id: "t8",
    name: "Mid-Atlantic Memorial",
    host: "DC Metro Soccer",
    city: "Arlington",
    state: "VA",
    region: "Northeast",
    dateStart: "2026-05-23",
    dateEnd: "2026-05-25",
    age: ["U10", "U11", "U12", "U13"],
    gender: "Boys",
    level: "Highest",
    format: "9v9",
    surface: "Grass",
    fee: 750,
    teams: 96,
    rating: 4.8,
    reviews: 187,
    status: "Open",
    featured: false,
    sanctioned: "US Soccer",
    spotsLeft: 4,
    mapX: 820, mapY: 295,
    img: null,
    scene: "capitol",
    tagline: "Memorial weekend tradition"
  },
  {
    id: "t9",
    name: "Desert Heat Tournament",
    host: "Arizona Soccer Assoc.",
    city: "Phoenix",
    state: "AZ",
    region: "Mountain",
    dateStart: "2026-11-07",
    dateEnd: "2026-11-09",
    age: ["U7", "U8", "U9", "U10", "U11"],
    gender: "Both",
    level: "Lower",
    format: "7v7",
    surface: "Grass",
    fee: 425,
    teams: 144,
    rating: 4.4,
    reviews: 62,
    status: "Open",
    featured: false,
    sanctioned: "Regional",
    spotsLeft: 26,
    mapX: 270, mapY: 410,
    img: null,
    scene: "desert",
    tagline: "Crisp November mornings"
  },
  {
    id: "t10",
    name: "Heartland Classic",
    host: "Kansas City Premier",
    city: "Kansas City",
    state: "MO",
    region: "Midwest",
    dateStart: "2026-09-12",
    dateEnd: "2026-09-13",
    age: ["U12", "U13", "U14", "U15", "U16"],
    gender: "Both",
    level: "Upper",
    format: "11v11",
    surface: "Grass",
    fee: 575,
    teams: 80,
    rating: 4.5,
    reviews: 44,
    status: "Open",
    featured: false,
    sanctioned: "US Club",
    spotsLeft: 22,
    mapX: 565, mapY: 325,
    img: null,
    scene: "prairie",
    tagline: "True midwest hospitality"
  },
  {
    id: "t11",
    name: "Atlanta Premier Cup",
    host: "Georgia Soccer League",
    city: "Atlanta",
    state: "GA",
    region: "Southeast",
    dateStart: "2026-10-10",
    dateEnd: "2026-10-12",
    age: ["U13", "U14", "U15", "U16", "U17", "U18", "U19"],
    gender: "Boys",
    level: "Highest",
    format: "11v11",
    surface: "Turf",
    fee: 1100,
    teams: 112,
    rating: 4.7,
    reviews: 203,
    status: "Open",
    featured: false,
    sanctioned: "US Soccer",
    spotsLeft: 9,
    mapX: 720, mapY: 445,
    img: null,
    scene: "field",
    tagline: "Recruiting hotbed"
  },
  {
    id: "t12",
    name: "Twin Cities Faceoff",
    host: "Minnesota Youth Soccer",
    city: "Minneapolis",
    state: "MN",
    region: "Midwest",
    dateStart: "2026-06-26",
    dateEnd: "2026-06-28",
    age: ["U10", "U11", "U12"],
    gender: "Girls",
    level: "Middle",
    format: "9v9",
    surface: "Grass",
    fee: 485,
    teams: 60,
    rating: 4.6,
    reviews: 38,
    status: "Open",
    featured: false,
    sanctioned: "Regional",
    spotsLeft: 14,
    mapX: 580, mapY: 220,
    img: null,
    scene: "lake",
    tagline: "Long days, short nights"
  }
];

// Filter taxonomies
window.TAXONOMIES = {
  ages: ["U4","U5","U6","U7","U8","U9","U10","U11","U12","U13","U14","U15","U16","U17","U18","U19"],
  genders: ["Boys","Girls","Both"],
  levels: ["Highest","Upper","Middle","Lower"],
  formats: ["3v3","5v5","7v7","9v9","11v11"],
  regions: ["West","Mountain","Midwest","South","Southeast","Northeast"],
  surfaces: ["Grass","Turf"]
};
